spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: asdcprojectuppe@gmail.com
    password: llzdtqvvtafevejw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    org.springframework.mail: DEBUG
